language: ruby

rvm:
  - ruby-2.3.0
  - 2.1.4
  - 2.1.2
  - 2.1.1
  - 2.1.0

before_install:
  - gem install bundler
  - rm -f .git/index.lock

script: "bundle exec rspec spec"

notifications:
  slack: sachin21dev:PVRFTzXu4ovOOkZYJ6fCISbq
